source 'https://rubygems.org'
ruby '2.3.3'

gem 'jekyll', '~> 3.4.0'
gem 'jekyll-sitemap'
gem 'jekyll-paginate'
gem 'jekyll-gist'
gem 'jekyll-feed'
gem 'jekyll-admin'
gem 'jemoji'
gem 'octopress', '~> 3.0.0.rc.12'
gem 'redcarpet', '~> 3.1'
gem 'listen'
gem 'compass'
gem 'celluloid', '<0.17.0'
#gem 'minimal-mistakes-jekyll'
